version: '3'

networks:
    symfNetwork:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfNetwork
        depends_on:
            - php
            - mysql

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/html
        networks:
            - symfNetwork

    mysql:
        image: mariadb
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: secret
        networks:
            - symfNetwork

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin1
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
        volumes:
            - /docker/sessions
        depends_on:
            - mysql
        restart: always
        networks: 
            - symfNetwork
   



